// UI strings and section copy. Facts (projects, resume, links) live in their own files.
const fa = {
  skip: 'رفتن به محتوا',
  nav: {
    label: 'ناوبری اصلی',
    work: 'کارها',
    experience: 'تجربه',
    about: 'درباره',
    blog: 'نوشته‌ها',
    resume: 'رزومه',
    github: 'GitHub',
    language: 'زبان',
    openMenu: 'باز کردن منو',
    closeMenu: 'بستن منو',
    command: 'باز کردن جست‌وجو',
    toDark: 'تم تیره',
    toLight: 'تم روشن',
    home: 'ستایش سهیلی، خانه',
  },
  hero: {
    kicker: 'برنامه‌نویس و طراح وبسایت در گرگان',
    viewProjects: 'همه‌ی پروژه‌ها',
    resume: 'رزومه',
    stats: { projects: 'پروژه', repos: 'مخزن عمومی', contributions: 'مشارکت در GitHub', tools: 'ابزار و تکنولوژی' },
    showcase: 'پروژه‌های منتخب',
    prev: 'پروژه‌ی قبلی',
    next: 'پروژه‌ی بعدی',
    goTo: (n: number) => `رفتن به پروژه‌ی ${n}`,
  },
  experience: {
    kicker: 'تجربه',
    title: 'روی چه کارهایی کار کرده‌ام.',
  },
  capabilities: {
    kicker: 'مهارت‌ها',
    title: 'ابزارهایی که با آن‌ها کار می‌کنم.',
    description: 'تکنولوژی‌هایی که در پروژه‌هایم به کار می‌برم؛ backend، ربات، automation و وب.',
    tools: (n: number) => `${n.toLocaleString('fa-IR')} مورد`,
    github: 'پروفایل GitHub',
  },
  activity: {
    kicker: 'فعالیت',
    title: 'فعالیت اخیر در GitHub.',
    description: 'مخزن‌های عمومی و فعالیت مهندسی، همان‌طور که در GitHub ثبت شده.',
    contributions: 'مشارکت در یک سال گذشته',
    less: 'کمتر',
    more: 'بیشتر',
    repositories: 'مخزن‌ها',
    recent: 'فعالیت اخیر',
    type: { commit: 'کامیت', release: 'انتشار', repo: 'مخزن جدید' },
    created: 'ایجاد شد',
  },
  about: {
    kicker: 'درباره',
    title: 'پیشینه و شیوه‌ی کار.',
    description: 'برنامه‌نویس ساکن گرگان، ایران.',
    lead: 'از شبکه شروع کردم و به نرم‌افزار رسیدم. بیشتر با Python، backend، ربات‌ها و automation کار می‌کنم و معمولاً در هر پروژه چیز تازه‌ای یاد می‌گیرم.',
    notes: [
      'علاقه‌ام فقط به نوشتن کد محدود نیست؛ دوست دارم بفهمم نرم‌افزاری که می‌سازم در دنیای واقعی چطور استفاده می‌شود.',
      'هنوز مسیرم در حال شکل گرفتن است، بنابراین ترجیح می‌دهم بیشتر با پروژه‌هایی که ساخته‌ام شناخته شوم تا با یک عنوان ثابت.',
    ],
    based: 'محل زندگی',
    focus: 'تمرکز',
    now: 'این روزها',
    nowText: 'الان بیشتر درگیر پروژه‌های واقعی، Python، backend، ربات‌ها و automation هستم و دارم مسیر بعدی کارم را از دل همین پروژه‌ها پیدا می‌کنم.',
  },
  contact: {
    kicker: 'تماس',
    channels: 'راه‌های ارتباط',
    text: 'اگر کاری، پروژه‌ای یا همکاری‌ای داری که فکر می‌کنی می‌تواند جالب باشد، می‌توانی با من در تماس باشی.',
    getInTouch: 'در تماس باشید',
  },
  work: {
    kicker: 'همه‌ی پروژه‌ها // آرشیو',
    title: 'چیزهایی که ساخته‌ام و روی آن‌ها کار کرده‌ام.',
    description: 'پروژه‌های منتخب ستایش سهیلی؛ نرم‌افزار، ربات‌های پیام‌رسان، automation و وب.',
    intro: 'آرشیو پروژه‌ها؛ از ابزارهای متن‌باز و ربات‌ها تا وب‌سایت و پروژه‌های آزمایشی.',
    count: (n: number) => `${n.toLocaleString('fa-IR')} پروژه`,
    earlier: 'پروژه‌های قدیمی‌تر',
    caseStudy: 'مشاهده‌ی پروژه',
    openLive: (name: string) => `باز کردن نسخه‌ی آنلاین ${name}`,
  },
  project: {
    back: 'بازگشت به همه‌ی پروژه‌ها',
    outline: 'فهرست پروژه',
    links: 'لینک‌ها',
    repository: 'مخزن',
    live: 'نسخه‌ی آنلاین',
    source: 'کد منبع',
    liveDeployment: 'نسخه‌ی آنلاین',
    githubRepository: 'مخزن GitHub',
    language: 'زبان',
    stars: 'ستاره',
    forks: 'فورک',
    release: 'آخرین انتشار',
    updated: 'به‌روزرسانی',
    created: 'ایجاد',
    license: 'مجوز',
    previous: 'پروژه‌ی قبلی',
    next: 'پروژه‌ی بعدی',
    gallery: 'تصاویر',
    writing: 'نوشته‌های مرتبط',
    kinds: { 'open-source': 'متن‌باز', client: 'پروژه‌ی مشتری', team: 'پروژه‌ی تیمی', experiment: 'آزمایشی', coursework: 'پروژه‌ی درسی' },
  },
  blog: {
    kicker: 'نوشته‌ها // یادداشت‌ها',
    title: 'یادداشت‌هایی درباره‌ی چیزهایی که می‌سازم.',
    description: 'یادداشت‌ها و نوشته‌های ستایش سهیلی درباره‌ی نرم‌افزار، backend، ربات‌ها و automation.',
    intro: 'نوشته‌های فنی، تصمیم‌های معماری و چیزهایی که از پروژه‌ها یاد گرفته‌ام.',
    count: (n: number) => `${n.toLocaleString('fa-IR')} نوشته‌ی منتشرشده`,
    empty: 'هنوز نوشته‌ای منتشر نشده است.',
    featured: 'ویژه',
    read: 'خواندن',
  },
  article: {
    back: 'همه‌ی نوشته‌ها',
    kicker: 'مقاله',
    outline: 'فهرست مقاله',
    details: 'مشخصات مقاله',
    published: 'انتشار',
    updated: 'به‌روزرسانی',
    readingTime: 'زمان مطالعه',
    minutes: (n: number) => `${n.toLocaleString('fa-IR')} دقیقه مطالعه`,
    tags: 'برچسب‌ها',
    share: 'اشتراک‌گذاری',
    linkCopied: 'لینک کپی شد',
    previous: 'نوشته‌ی قبلی',
    next: 'نوشته‌ی بعدی',
    related: 'پروژه‌ی مرتبط',
  },
  resume: {
    kicker: 'رزومه',
    title: 'رزومه',
    description: 'رزومه‌ی ستایش سهیلی، برنامه‌نویس در گرگان: تجربه، مهارت‌های فنی و زبان‌ها.',
    intro: 'تجربه، مهارت‌ها و زبان‌ها — نسخه‌ی قابل چاپ این صفحه جای فایل PDF را می‌گیرد.',
    experience: 'تجربه',
    education: 'تحصیلات',
    capabilities: 'مهارت‌ها',
    languages: 'زبان‌ها',
    certificates: 'گواهی‌نامه‌ها',
    print: 'چاپ / ذخیره به PDF',
    view: 'مشاهده',
  },
  command: {
    placeholder: 'جست‌وجو در بخش‌ها، پروژه‌ها و نوشته‌ها…',
    label: 'جست‌وجو',
    empty: 'نتیجه‌ای پیدا نشد.',
    types: { section: 'بخش', page: 'صفحه', project: 'پروژه', article: 'مقاله', action: 'فرمان', link: 'لینک' },
    home: 'خانه',
    toggleTheme: 'تغییر تم',
    switchLanguage: 'English',
  },
  rail: 'پروژه‌ها',
  tickerSkills: 'مهارت‌ها',
  tickerProjects: 'پروژه‌های منتخب',
  dock: 'راه‌های ارتباط',
  section: 'بخش',
  copy: 'کپی',
  copied: 'کپی شد',
}

const en: typeof fa = {
  skip: 'Skip to content',
  nav: {
    label: 'Primary navigation',
    work: 'Work',
    experience: 'Experience',
    about: 'About',
    blog: 'Blog',
    resume: 'Résumé',
    github: 'GitHub',
    language: 'Language',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    command: 'Open command menu',
    toDark: 'Switch to dark theme',
    toLight: 'Switch to light theme',
    home: 'Setayesh Soheili, home',
  },
  hero: {
    kicker: 'Software Engineer',
    viewProjects: 'View all projects',
    resume: 'Résumé',
    stats: { projects: 'Projects', repos: 'Public repos', contributions: 'GitHub contributions', tools: 'Tech & tools' },
    showcase: 'Featured projects',
    prev: 'Previous project',
    next: 'Next project',
    goTo: (n: number) => `Go to project ${n}`,
  },
  experience: {
    kicker: 'Experience',
    title: 'What I have been working on.',
  },
  capabilities: {
    kicker: 'Capabilities',
    title: 'The tools I work with.',
    description: 'Technologies from my projects: backend systems, bots, automation, and the web.',
    tools: (n: number) => `${n} tools`,
    github: 'View GitHub profile',
  },
  activity: {
    kicker: 'Activity',
    title: 'Recent work on GitHub.',
    description: 'Public repositories and engineering activity, as recorded on GitHub.',
    contributions: 'contributions in the last year',
    less: 'Less',
    more: 'More',
    repositories: 'Repositories',
    recent: 'Recent activity',
    type: { commit: 'Commit', release: 'Release', repo: 'New repo' },
    created: 'created',
  },
  about: {
    kicker: 'About',
    title: 'Background and how I work.',
    description: 'A software engineer based in Gorgan, Iran.',
    lead: 'I started with networking and eventually moved into software development. I mostly work with Python, backend systems, bots, and automation, and I tend to learn something new from every project.',
    notes: [
      'My interest goes beyond writing code. I like understanding how the software I build actually works in the real world.',
      'My path is still taking shape, so I would rather be known for the projects I have built than for a fixed title.',
    ],
    based: 'Based in',
    focus: 'Focus',
    now: 'Currently',
    nowText: 'Currently building software, working with real projects, and figuring out what comes next.',
  },
  contact: {
    kicker: 'Contact',
    channels: 'Direct channels',
    text: 'For projects, collaborations, or interesting work, feel free to get in touch.',
    getInTouch: 'Get in touch',
  },
  work: {
    kicker: 'All projects // Archive',
    title: 'Things I have built and worked on.',
    description: 'Selected projects by Setayesh Soheili: software, messaging bots, automation, and web systems.',
    intro: 'An archive of projects — open-source tools and bots, websites, and experiments.',
    count: (n: number) => `${n} projects`,
    earlier: 'Earlier projects',
    caseStudy: 'View case study',
    openLive: (name: string) => `Open ${name} live site`,
  },
  project: {
    back: 'Back to all projects',
    outline: 'Project Outline',
    links: 'Links',
    repository: 'Repository',
    live: 'Live Preview',
    source: 'Source Code',
    liveDeployment: 'Live Deployment',
    githubRepository: 'GitHub Repository',
    language: 'Language',
    stars: 'Stars',
    forks: 'Forks',
    release: 'Latest release',
    updated: 'Updated',
    created: 'Created',
    license: 'License',
    previous: 'Previous Project',
    next: 'Next Project',
    gallery: 'Screenshots',
    writing: 'Writing about this project',
    kinds: { 'open-source': 'Open source', client: 'Client project', team: 'Team project', experiment: 'Experiment', coursework: 'Coursework' },
  },
  blog: {
    kicker: 'Writing // Notes',
    title: 'Notes on what I build.',
    description: 'Notes and articles by Setayesh Soheili on software, backend development, bots, and automation.',
    intro: 'Technical notes, architecture decisions, and what I learn from building real projects.',
    count: (n: number) => `${n} published article${n === 1 ? '' : 's'}`,
    empty: 'Nothing published yet.',
    featured: 'Featured',
    read: 'Read',
  },
  article: {
    back: 'All Articles',
    kicker: 'Article',
    outline: 'Article Outline',
    details: 'Article Details',
    published: 'Published',
    updated: 'Updated',
    readingTime: 'Reading Time',
    minutes: (n: number) => `${n} min read`,
    tags: 'Tags',
    share: 'Share article',
    linkCopied: 'Link copied',
    previous: 'Previous Note',
    next: 'Next Note',
    related: 'Related project',
  },
  resume: {
    kicker: 'Résumé',
    title: 'Resume',
    description: 'Resume of Setayesh Soheili, Software Engineer in Gorgan, Iran: experience, technical skills, and languages.',
    intro: 'Experience, capabilities, and languages — print this page to get a PDF.',
    experience: 'Experience',
    education: 'Education',
    capabilities: 'Capabilities',
    languages: 'Languages',
    certificates: 'Certificates',
    print: 'Print / Save as PDF',
    view: 'View',
  },
  command: {
    placeholder: 'Type a command or search…',
    label: 'Search sections, projects, or actions',
    empty: 'No results.',
    types: { section: 'Section', page: 'Page', project: 'Project', article: 'Article', action: 'Action', link: 'Link' },
    home: 'Home',
    toggleTheme: 'Toggle theme',
    switchLanguage: 'فارسی',
  },
  rail: 'Projects',
  tickerSkills: 'Core engineering skills',
  tickerProjects: 'Featured projects',
  dock: 'Direct connections and profiles',
  section: 'Section',
  copy: 'Copy',
  copied: 'Copied',
}

export const copy = { fa, en }
export type Copy = typeof fa
